#!/usr/bin/env python3
"""Extract the IQ2_S lookup tables from the llama.cpp source, verbatim.

`block_iq2_s` needs two tables from upstream: `iq2s_grid` (1024 uint64 entries, each 8 grid
values) and `kmask_iq2xs` (8 sign masks). They are arbitrary data, so they are EXTRACTED from
the source that llama.cpp itself compiles rather than retyped — a single transcription slip in
1024 entries would be invisible in a dequant that still "looks plausible".

Writes native/gguf/iq2s_tables.py (generated; do not hand-edit) with the source path, the
upstream commit, and the tables.

  LLAMA_CPP_SRC=~/Projects/llama.cpp python3 native/tools/gen_iq2s_tables.py
"""
import os
import re
import subprocess
import sys

SRC = os.environ.get("LLAMA_CPP_SRC", os.path.expanduser("~/Projects/llama.cpp"))
COMMON_H = os.path.join(SRC, "ggml/src/ggml-common.h")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "gguf/iq2s_tables.py")


def extract_table(text, name, count):
    """GGML_TABLE_BEGIN(<type>, <name>, <count>) ... GGML_TABLE_END() -> list[int]"""
    m = re.search(r"GGML_TABLE_BEGIN\([^,]+,\s*" + re.escape(name) + r",\s*" + str(count) + r"\)",
                  text)
    if not m:
        sys.exit(f"table {name} not found in {COMMON_H}")
    end = text.find("GGML_TABLE_END()", m.end())
    if end < 0:
        sys.exit(f"table {name}: no GGML_TABLE_END")
    body = text[m.end():end]
    # Upstream writes some tables in hex (iq2s_grid) and some in decimal (kmask_iq2xs), so accept
    # both. Comments are stripped first so a stray number in prose cannot be read as data.
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    vals = [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\d+", body)]
    if len(vals) != count:
        sys.exit(f"table {name}: extracted {len(vals)} entries, expected {count}")
    return vals


def main():
    if not os.path.exists(COMMON_H):
        sys.exit(f"not found: {COMMON_H} (set LLAMA_CPP_SRC)")
    text = open(COMMON_H, encoding="utf-8", errors="replace").read()

    grid = extract_table(text, "iq2s_grid", 1024)
    kmask = extract_table(text, "kmask_iq2xs", 8)

    try:
        commit = subprocess.run(["git", "-C", SRC, "rev-parse", "HEAD"],
                                capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        commit = "unknown (not a git checkout)"

    size = 2 + 256 // 4 + 256 // 16      # d f16 + qs[64] + qh[8] + scales[8]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write('"""IQ2_S lookup tables — GENERATED by native/tools/gen_iq2s_tables.py.\n\n')
        fh.write("Extracted verbatim from llama.cpp (MIT License, https://github.com/ggml-org/llama.cpp):\n")
        fh.write(f"  {os.path.relpath(COMMON_H, os.path.expanduser('~'))}\n")
        fh.write(f"  commit {commit}\n\n")
        fh.write("Do not hand-edit: re-run the generator so the data cannot drift from the source it\n")
        fh.write("is supposed to be a faithful copy of.\n\"\"\"\n\n")
        fh.write(f"# block_iq2_s is {size} bytes: d f16 @0, qs[64] @2, qh[8] @66, scales[8] @74.\n")
        fh.write(f"IQ2_S_BLOCK_BYTES = {size}\n")
        fh.write("IQ2_S_GRID_ENTRIES = 1024\n\n")
        fh.write("# uint8_t kmask_iq2xs[8]\n")
        fh.write(f"IQ2_S_KMASK = {tuple(kmask)!r}\n\n")
        fh.write("# uint64_t iq2s_grid[1024]; entry i is 8 grid bytes, LOW byte first (little-endian).\n")
        fh.write("IQ2_S_GRID = (\n")
        for i in range(0, len(grid), 8):
            fh.write("    " + " ".join(f"0x{v:016x}," for v in grid[i:i + 8]) + "\n")
        fh.write(")\n")
    print(f"wrote {OUT}")
    print(f"  iq2s_grid: {len(grid)} entries, commit {commit}")
    print(f"  kmask_iq2xs: {kmask}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
