#!/usr/bin/env python3
"""Gate for the real-model llm.chat closed loop (make -f native/Makefile chat-real).

Runs the full 36-layer Qwen3-4B forward over a REAL prompt (CHAT_PROMPT, ids from
the model's own tokenizer), takes the tied lm_head argmax per position, and decodes
the argmax ids back to text through the stdlib/vllm CPU head. Asserts:

  - the run really used a text prompt (PROMPT_MODE=text + PROMPT_SRC), not the
    synthetic [0,1] prefix -- on a 2-character punctuation input the decoded text
    is meaningless by construction and cannot be gated on
  - per-position top1 argmax ids == the numpy gold (prompt_ref.py), regenerated by
    the make target on every run
  - the final hidden still matches the numpy reference for the same prompt (maxrel)
  - a real decoded response is present and contains ASCII letters (English)

Reads native/out/chat_real.log, prefill_top1_vyb.txt, prefill_hidden_vyb.txt
(driver outputs) and prompt_top1_ref.txt, prompt_hidden_ref.txt (numpy gold).
"""
import os, re, numpy as np

repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
log = os.path.join(repo, "native/out/chat_real.log")
ok = True

if not os.path.exists(log):
    print("MISSING chat_real.log — run the driver first")
    raise SystemExit(2)
txt = open(log).read()

# 0. the run must have used a real prompt
if "PROMPT_MODE=text" not in txt:
    print("FAIL: log is not a text-prompt run (expected PROMPT_MODE=text).")
    print("      The synthetic [0,1] prefix has no linguistic input, so its decoded")
    print("      text cannot be gated on — use `make prefill` for numeric checks.")
    raise SystemExit(1)
msrc = re.search(r"PROMPT_SRC=<(.*?)>", txt)
print(f"  prompt = <{msrc.group(1) if msrc else '(missing)'}>")
if not msrc:
    ok = False

# 1. per-position top1 argmax vs the numpy gold for the SAME prompt
ref_p = os.path.join(repo, "native/out/prompt_top1_ref.txt")
got_p = os.path.join(repo, "native/out/prefill_top1_vyb.txt")
if not (os.path.exists(ref_p) and os.path.exists(got_p)):
    print("FAIL: missing prompt_top1_ref.txt / prefill_top1_vyb.txt")
    ok = False
else:
    gold = np.loadtxt(ref_p, dtype=int)
    got = np.loadtxt(got_p, dtype=int)
    if gold.size != got.size:
        print(f"FAIL: size mismatch gold={gold.size} gpu={got.size}")
        ok = False
    else:
        match = bool((gold == got).all())
        print(f"  per-position top1 gpu = {got.tolist()}")
        print(f"  per-position top1 gold= {gold.tolist()}")
        print(f"  last position (next token after the prompt) = {int(got[-1])}")
        print("CHAT_TOP1_MATCH:", "OK" if match else "FAIL")
        if not match:
            for i in range(gold.size):
                if gold[i] != got[i]:
                    print(f"    tok{i}: gold={gold[i]} gpu={got[i]}   <-- MISMATCH")
            ok = False

# 2. final hidden vs the numpy reference for the same prompt
ref_h = os.path.join(repo, "native/out/prompt_hidden_ref.txt")
got_h = os.path.join(repo, "native/out/prefill_hidden_vyb.txt")
if os.path.exists(ref_h) and os.path.exists(got_h):
    ref = np.loadtxt(ref_h); vyb = np.loadtxt(got_h)
    if ref.size == vyb.size:
        rel = np.abs(vyb - ref) / np.maximum(np.abs(ref), 1e-6)
        bad = int((rel > 2e-3).sum())
        print(f"  hidden vs numpy (same prompt): bad(rel>2e-3) = {bad}  maxrel = {rel.max():.3e}")
        print("CHAT_HIDDEN_MATCH:", "OK" if bad == 0 else "FAIL")
        if bad:
            ok = False
    else:
        print(f"  hidden size mismatch gpu={vyb.size} ref={ref.size} — FAIL")
        ok = False

# 3. a real decoded continuation, in English
mr = re.search(r"LLM_CHAT_RESPONSE=<(.*)>\n", txt)
if not mr:
    print("FAIL: no LLM_CHAT_RESPONSE line in log")
    ok = False
else:
    resp = mr.group(1)
    present = len(resp) > 0
    ascii_letters = sum(1 for ch in resp if ch.isascii() and ch.isalpha())
    print(f"  response decoded: <{resp}> ({len(resp)} chars, {ascii_letters} ASCII letters)")
    print("LLM_CHAT_RESPONSE_PRESENT:", "OK" if present else "FAIL")
    print("LLM_CHAT_RESPONSE_ENGLISH:", "OK" if ascii_letters > 0 else "FAIL")
    if not present or ascii_letters == 0:
        ok = False

print("\nCHAT-REAL:", "PASS" if ok else "FAIL")
raise SystemExit(0 if ok else 1)
